server:
  port: 8080

spring:
  application:
    name: online-tools

  # Configuration for AWS S3
  # Configuration for AWS S3
  # aws:
  #   s3:
  #     region: ${AWS_S3_REGION:ap-southeast-1}
  #     bucket-name: ${AWS_S3_BUCKET_NAME:your-bucket-name}
  #     access-key: ${AWS_S3_ACCESS_KEY:your-access-key}
  #     secret-key: ${AWS_S3_SECRET_KEY:your-secret-key}

  # Springdoc OpenAPI configuration
# springdoc:
#   api-docs:
#     path: /api-docs
#   swagger-ui:
#     path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    defaults:
      enabled: true
